### ISSUE TITLE
Unable to build - cannot find value `kAudioAggregateDevicePropertyMainSubDevice`

### ISSUE THREAD

**Issue by orottier** [mozilla/cubeb-coreaudio-rs#264]
I'm running on an Apple M1 MacOs Monterey 12.7.5 (21H1222)

```
     Compiling cubeb-coreaudio v0.1.0 (/Users/otto/Projects/cubeb-coreaudio-rs/target/debug/build/cubeb-sys-2332bf7670df836e/out/libcubeb/src/cubeb-coreaudio-rs)
  error[E0425]: cannot find value `kAudioAggregateDevicePropertyMainSubDevice` in this scope
       --> src/backend/aggregate_device.rs:480:24
        |
    480 |             mSelector: kAudioAggregateDevicePropertyMainSubDevice,
        |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `kAudioAggregateDevicePropertyMasterSubDevice`
        |
       ::: /Users/otto/Projects/cubeb-coreaudio-rs/target/debug/build/cubeb-sys-2332bf7670df836e/out/libcubeb/src/cubeb-coreaudio-rs/target/aarch64-apple-darwin/debug/build/coreaudio-sys-f51196324b61f2da/out/coreaudio.rs:20335:1
        |
  20335 | pub const kAudioAggregateDevicePropertyMasterSubDevice: _bindgen_ty_273 = 1634562932;
        | ----------------------------------------------------------------------- similarly named constant `kAudioAggregateDevicePropertyMasterSubDevice` defined here

  error[E0425]: cannot find value `kAudioAggregateDevicePropertyMainSubDevice` in this scope
       --> src/backend/aggregate_device.rs:515:24
        |
    515 |             mSelector: kAudioAggregateDevicePropertyMainSubDevice,
        |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `kAudioAggregateDevicePropertyMasterSubDevice`
        |
       ::: /Users/otto/Projects/cubeb-coreaudio-rs/target/debug/build/cubeb-sys-2332bf7670df836e/out/libcubeb/src/cubeb-coreaudio-rs/target/aarch64-apple-darwin/debug/build/coreaudio-sys-f51196324b61f2da/out/coreaudio.rs:20335:1
        |
  20335 | pub const kAudioAggregateDevicePropertyMasterSubDevice: _bindgen_ty_273 = 1634562932;
        | ----------------------------------------------------------------------- similarly named constant `kAudioAggregateDevicePropertyMasterSubDevice` defined here
```

The latest version I can build on this machine is cubeb-sys 0.15

**Comment by kinetiknz** [comment]
Which version of the macOS SDK are you using? `kAudioAggregateDevicePropertyMainSubDevice` is only available in >= 12.0.

**Comment by orottier** [comment]
Aha, that is probably it:

```
➜  cubeb-sys git:(master) xcrun --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
➜  cubeb-sys git:(master) ls -l /Library/Developer/CommandLineTools/SDKs
total 0
lrwxr-xr-x  1 root  wheel   14 19 mei  2021 MacOSX.sdk -> MacOSX11.3.sdk
drwxr-xr-x  8 root  wheel  256 19 mei  2021 MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 30 nov  2020 MacOSX11.1.sdk
drwxr-xr-x  7 root  wheel  224 16 mrt  2021 MacOSX11.3.sdk
lrwxr-xr-x  1 root  wheel   14 19 mei  2021 MacOSX11.sdk -> MacOSX11.3.sdk
```

I can't update right now, so will try that later. Will let you know if I run into anything else. Thanks!
